services:
  - type: web
    name: nse-stocks-mobile
    env: static
    buildCommand: ""
    staticPublishPath: ./frontend/mobile
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /*.png
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.css
        name: Cache-Control
        value: public, max-age=86400
      - path: /*.js
        name: Cache-Control
        value: public, max-age=0, must-revalidate
